### ISSUE TITLE
Warning: call_user_func_array() ...

### ISSUE THREAD

**Issue by bbarnwell** [timber/sugar#5]
Tried adding some Sugar. Got this. Ideas?

Warning: call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object in C:\wamp\www\wp\wp-content\plugins\timber-library\vendor\twig\twig\lib\Twig\Environment.php(403) : eval()'d code on line 51

**Comment by jarednova** [comment]
what did you call to trigger this error? or is this from just installing?

**Comment by bbarnwell** [comment]
Called this, as per instructions:

{{dummy(500)|wpautop}}

**Comment by jarednova** [comment]
@bbarnwell — give `master` a check now: looks like there were some functions that should have been `static`

**Comment by bbarnwell** [comment]
Works like a charm! Thanks guys. Nice work.
